### ISSUE TITLE
RPC errors while parsing data.

### ISSUE THREAD

**Issue by effofxprime** [forbole/bdjuno#391]
bdjuno is parsing through Vidulums blockchain data.

I am having a lot of errors regarding handling the block.  When I first compiled the bdjuno, I was using v3.  v3 had less of these errors but I had that inconsistent metadata issue.  So I deleted my original repo clone.  What sucks, is I have been unable to recompile a v3.
I know I was running a v3 bdjuno binary because my start command for it was `bdjuno start` rather than `bdjuno parse`

The below errors are coming from v2.  

```
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM DBG updating validators height=164488 module=staking
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM ERR error while handling block err="error while updating validators: error while getting validator: rpc error: code = Unavailable desc = connection closed" height=164488 module=staking
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM DBG enqueueing missing block height=164516
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM DBG updating signing info height=164489 module=slashing
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM ERR error while handling block err="error while updating signing info: rpc error: code = Unavailable desc = connection closed" height=164489 module=slashing
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM DBG updating validators height=164489 module=staking
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM ERR error while handling block err="error while updating validators: error while getting validator: rpc error: code = Unavailable desc = connection closed" height=164489 module=staking
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM DBG enqueueing missing block height=164517
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM DBG processing block height=164490
Apr 14 19:27:16 erialos.me bdjuno[66792]: 7:27PM DBG processing block height=164491
```

**Comment by effofxprime** [comment]
When I run `bdjuno parse genesis-file` I am getting
```
bdcosmos@erialos:~/bdjuno-v3$ bdjuno parse genesis-file
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14da738]

goroutine 1 [running]:
github.com/forbole/bdjuno/v3/modules/actions.NewModule({{0xc000d74500, 0x4f9, 0x4fa}, {{0xc000d1198d, 0x3}, {0xc00015e540, 0xc, 0xc}}, {{0x190fbb3, 0x4}, ...}, ...}, ...)
        /home/bdcosmos/bdjuno-v3/modules/actions/module.go:41 +0x98
github.com/forbole/bdjuno/v3/modules.(*Registrar).BuildModules(_, {{{0xc000d74500, 0x4f9, 0x4fa}, {{0xc000d1198d, 0x3}, {0xc00015e540, 0xc, 0xc}}, {{0x190fbb3, ...}, ...}, ...}, ...})
        /home/bdcosmos/bdjuno-v3/modules/registrar.go:74 +0xf8
github.com/forbole/juno/v3/cmd/parse/types.GetParserContext({{0xc000d74500, 0x4f9, 0x4fa}, {{0xc000d1198d, 0x3}, {0xc00015e540, 0xc, 0xc}}, {{0x190fbb3, 0x4}, ...}, ...}, ...)
        /home/bdcosmos/go/pkg/mod/github.com/forbole/juno/v3@v3.1.1/cmd/parse/types/setup.go:57 +0x7d8
github.com/forbole/juno/v3/cmd/parse/genesis.NewGenesisCmd.func1(0xc000d6b180?, {0x2a475b0?, 0x0?, 0x0?})
        /home/bdcosmos/go/pkg/mod/github.com/forbole/juno/v3@v3.1.1/cmd/parse/genesis/cmd.go:37 +0x165
github.com/spf13/cobra.(*Command).execute(0xc000d6b180, {0x2a475b0, 0x0, 0x0})
        /home/bdcosmos/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000cb1b80)
        /home/bdcosmos/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/bdcosmos/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/tendermint/tendermint/libs/cli.Executor.Execute({0xc000cb1b80?, 0x1b92b08?})
        /home/bdcosmos/go/pkg/mod/github.com/forbole/tendermint@v0.34.13-0.20210820072129-a2a4af55563d/libs/cli/setup.go:89 +0x4a
main.main()
        /home/bdcosmos/bdjuno-v3/cmd/bdjuno/main.go:47 +0x30a
```

That is with the following config.yaml
```
chain:
    bech32_prefix: vdl
    modules:
    - modules
    - messages
    - auth
    - bank
    - consensus
    - gov
    - mint
    - pricefeed
    - slashing
    - staking
    - distribution
    - history
node:
    type: remote
    config:
        rpc:
            client_name: bdcosmos
            address: https://trpc.rpc.erialos.me:443
            max_connections: 100
        grpc:
            address: https://grpc.rpc.erialos.me:443
            insecure: true
parsing:
    workers: 2
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 6s
    genesis_file_path: /home/bdcosmos/.bdjuno/genesis.json
database:
    name: bdcosmos
    host: localhost
    port: 5432
    user: bdcosmos
    password: ***
    schema: public
    max_open_connections: 18
    max_idle_connections: 13
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
telemetry:
    enabled: false
    port: 5000
pruning:
    keep_recent: 0
    keep_every: 0
    interval: 0
pricefeed:
    tokens:
        - name: Vidulum
          units:
            - denom: uvdl
              exponent: 0
            - denom: vdl
              exponent: 6
              price_id: vidulum

```

I backed that up by renaming it and issued `bdjuno init` to have a new config generated.  `On branch cosmos/v0.44.x`
When I have a new generated config file, it contains:
```
chain:
    bech32_prefix: vdl
    modules: []
node:
    type: remote
    config:
        rpc:
            client_name: bdcosmos
            address: https://trpc.rpc.erialos.me:443
            max_connections: 100
        grpc:
            address: https://grpc.rpc.erialos.me:443
            insecure: false
parsing:
    workers: 2
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 6s
    genesis_file_path: /home/bdcosmos/.bdjuno/genesis.json
database:
    name: bdcosmos
    host: localhost
    port: 5432
    user: bdcosmos
    password: 4juVuPPnkB*73JGj
    schema: public
    max_open_connections: 10
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
actions:
    port: 3000
```

`actions` isn't defined in https://docs.bigdipper.live/cosmos-based/parser/config/config

So I am assuming that there is something in my old config that is causing the halt of the `bdjuno` binary.

Have I missed some steps or am I just here "too early" and there hasn't been documentation on what I am seeing yet?

**Comment by effofxprime** [comment]
I am indeed able to connect to my RPC websock endpoint but only in a secure maner.  I have everything being redirected to ssl/https and then proxy passed through nginx on my rpc server.

```
 bdcosmos@erialos:~/.bdjuno$ ~/node_modules/wscat/bin/wscat -c wss://trpc.rpc.erialos.me/websocket
Connected (press CTRL+C to quit)
> bdcosmos@erialos:~/.bdjuno$ nano config.yaml
bdcosmos@erialos:~/.bdjuno$ ~/node_modules/wscat/bin/wscat -c wss://trpc.rpc.erialos.me/websocket
Connected (press CTRL+C to quit)
> bdcosmos@erialos:~/.bdjuno$ ~/node_modules/wscat/bin/wscat -c ws://trpc.rpc.erialos.me/websocket
error: Unexpected server response: 301
> bdcosmos@erialos:~/.bdjuno$ ~/node_modules/wscat/bin/wscat -c ws://trpc.rpc.erialos.me:26657/websocket
error: Unexpected server response: 400
> bdcosmos@erialos:~/.bdjuno$ ~/node_modules/wscat/bin/wscat -c wss://trpc.rpc.erialos.me:26657/websocket
Connected (press CTRL+C to quit)
```

You can see from above that I was able to connect to my RPC server via websocket only on a secure websock path.  Is this definable in the configuration?

**Comment by effofxprime** [comment]
Well, I cannot catch a break.  I think that this error stems from the version of the cosmos sdk and tendermint that Vidulum uses but, on the v2 build when running the `bdjuno parse` I eventually run into this:
```
Apr 14 21:26:47 rpc vidulumd[48557]: fatal error: concurrent map writes
```
The RPC daemon crashes and restarts.
This wasn't happening prior when running the v3 bdjuno.

**Comment by effofxprime** [comment]
Today I spent playing around with Nginx.  I specifically made the websocket non-ssl and ensured I was able to connect to it like I tested above.
Even though I am connecting to my RPC server via the websocket, running `bdjuno parse staking validators` will fail.
```
bdcosmos@erialos:~/2-bdjuno/bdjuno$ bdjuno parse staking validators
ERROR: error while getting validators: rpc error: code = Unavailable desc = connection closed
bdcosmos@erialos:~/2-bdjuno/bdjuno$ ~/node_modules/wscat/bin/wscat -c ws://trpc.rpc.erialos.me:26657/websocket
Connected (press CTRL+C to quit)
>
< {
  "jsonrpc": "2.0",
  "error": {
    "code": -32700,
    "message": "Parse error. Invalid JSON",
    "data": "error unmarshaling request: EOF"
  }
}
```

One thing I have noticed in this is that if I let the connection from `wscat` sit there, it will time out.
```
Disconnected (code: 1006, reason: "")
```

And looking at the RPC daemon logs:
```
Apr 15 18:56:45 rpc vidulumd[51680]: 6:56PM ERR Failed to read request err="websocket: close 1006 (abnormal closure): unexpected EOF" module=rpc-server protocol=websocket remote={"Name":"@","Net":"unix"}
Apr 15 18:56:45 rpc vidulumd[51680]: 6:56PM ERR error while stopping connection error="already stopped" module=rpc-server protocol=websocket

```
This was the recorded log events at the same time I was auto disconnected.

What is interesting is that the log events for failing the command `bdjuno parse staking validators` has similar log entry's:
```
Apr 15 18:58:32 rpc vidulumd[51680]: 6:58PM ERR Failed to read request err="websocket: close 1006 (abnormal closure): unexpected EOF" module=rpc-server protocol=websocket remote={"Name":"@","Net":"unix"}
Apr 15 18:58:32 rpc vidulumd[51680]: 6:58PM ERR error while stopping connection error="already stopped" module=rpc-server protocol=websocket
Apr 15 18:58:32 rpc vidulumd[51680]: 6:58PM ERR Failed to read request err="websocket: close 1006 (abnormal closure): unexpected EOF" module=rpc-server protocol=websocket remote={"Name":"@","Net":"unix"}
Apr 15 18:58:32 rpc vidulumd[51680]: 6:58PM ERR error while stopping connection error="already stopped" module=rpc-server protocol=websocket
Apr 15 18:58:32 rpc vidulumd[51680]: 6:58PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
Apr 15 18:58:32 rpc vidulumd[51680]: 6:58PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
Apr 15 18:58:32 rpc vidulumd[51680]: 6:58PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
```

**Comment by MonikaCat** [comment]
Hi @effofxprime thanks for reporting that. Has this issue been fixed now? Coz I tried running bdjuno cmds using your branch `v3/chains/vidulum/mainnet` and your config.yaml file and it works fine on my end.

**Comment by effofxprime** [comment]
@MonikaCat Thank you for getting back with me! :D
So, you don't get an rpc error when trying to run `bdjuno parse staking validators` ?  I just tried again from my end and have the same error.
```
:~$ bdjuno parse staking validators
ERROR: error while getting validators: rpc error: code = Unavailable desc = connection closed
```

**Comment by effofxprime** [comment]
To update, here is the current config i am using.  I have tried http/https/tcp.  I have just decided to leave it on tcp:// for now unless otherwise advised to not do so.
```
chain:
    bech32_prefix: vdl
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - pricefeed
        - slashing
        - staking
        - distribution
        #- history
node:
    type: remote
    config:
        rpc:
            client_name: bdcosmos
            address: tcp://trpc.rpc.erialos.me:26657
            max_connections: 20
        grpc:
            address: grpc.rpc.erialos.me:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 5s
    genesis_file_path: /home/bdcosmos/.bdjuno/genesis.json
database:
    name: bdcosmos
    host: 127.0.0.1
    port: 5432
    user: bdcosmos
    password: ***
    schema: public
    max_open_connections: 13
    max_idle_connections: 5
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
actions:
    port: 3000
telemetry:
    enabled: false
    port: 5000
pruning:
    keep_recent: 0
    keep_every: 0
    interval: 0
pricefeed:
    tokens:
        - name: Vidulum
          units:
            - denom: uvdl
              exponent: 0
            - denom: vdl
              exponent: 6
              price_id: vidulum
```

Just so we are on the same page too.
```
bdcosmos@erialos:~/bdjuno$ git show --summary
commit 9591e99010a00499b96e579f5ce82cc6bba674c9 (HEAD -> origin/v3/chains/vidulum/mainnet, tag: v3.0.1, upstream/cosmos/v0.44.x, origin/v3/chains/vidulum/mainnet, origin/cosmos/v0.44.x, origin/HEAD, cosmos/v0.44.x)
Author: Riccardo Montagnin <***>
Date:   Tue Apr 12 15:51:29 2022 +0200

    chore: release v3.0.1
```

**Comment by effofxprime** [comment]
Updated the vidulum branch i created with the latest cosmos/x0.44.x

```
commit 50452cae998a9437568d6b315dca042c8401e11f (HEAD -> origin/v3/chains/vidulum/mainnet, origin/origin/v3/chains/vidulum/mainnet)
Merge: 9989ef8 9e8c004
Author: effofxprime <effofxprime@gmail.com>
Date:   Wed Apr 20 14:05:37 2022 -0600

    Merge branch 'cosmos/v0.44.x' into origin/v3/chains/vidulum/mainnet
```

I did a `go mod tidy` `make clean` and `make isntall`

Still the same error when running `bdjuno parse staking validators`

@MonikaCat Just to confirm, you were able to connect to my RPC via websocket on your machine and config of bdjuno?

I still haven't quite figured out yet why I cannot connect via WebSocket with bdjuno.  I run a custom version of the PingPub explorer, and it is able to use my RPC node fine.  I do occasionally get a consecutive read & write error but it's never had an issue with communicating to it to query blockchain information.

**Comment by MonikaCat** [comment]
Hi @effofxprime I was able to connect before but I just tested it again and now I am getting the same error as you. Can you try to pass your node IP instead of custom address in rpc/grpc field?

**Comment by effofxprime** [comment]
the servers IP is `194.195.209.168` for reference.

Just tried your suggestion, and tried using tcp:// and http:// but neither worked.  I also changed this for the grpc as well.  With grpc, if I use tcp://, it will complain about too many colons but if i use http:// or just leave it blank, there is no complaint.

`ERROR: error while getting validators: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address tcp://194.195.209.168:9090: too many colons in address"`

I'll share my nginx config, maybe it's something to do with that?  I do find it odd that it worked and then stopped working.
Nginx has been the biggest thing that I've changed in my attempts to get this to work.  

RPC Nginx for tendermint rpc:
```

upstream tendermint_rpc {
        server unix:///dev/shm/vidulum/trpc.socket;
        #        weight=3 max_conns=1000 max_fails=1000 fail_timeout=360s;
        keepalive 60;
}


server {
        listen 443 ssl;
        listen 194.195.209.168:26657;

        server_name trpc.rpc.erialos.me;

#        limit_conn servers 100;
#        limit_req zone=request burst=10 delay=3;
#        limit_rate_after 3m;
#        limit_rate $response_rate;


        error_log /var/log/nginx/26657_error.log;

        ssl_certificate_key         /etc/letsencrypt/live/rpc.erialos.me/privkey.pem;
        ssl_certificate             /etc/letsencrypt/live/rpc.erialos.me/fullchain.pem;

        location / {
            proxy_headers_hash_bucket_size 128;

            proxy_pass http://tendermint_rpc;

            #ssl certs
            #proxy_ssl_trusted_certificate   /etc/letsencrypt/archive/rpc.erialos.me/chain2.pem;
            #proxy_ssl_certificate           /etc/letsencrypt/arhcive/rpc.erialos.me/privkey2.pem;
            #proxy_ssl_certificate_key       /etc/letsencrypt/archive/rpc.erialos.me/fullchain2.pem;

            #
            # These proxy settings were required for tendermint rpc to work/display properly via web
            #
            proxy_hide_header   Access-Control-Allow-Origin;
            proxy_set_header           Connection "Keep-Alive";

            #
            # Pingpub CORS proxy
            #
            proxy_set_header Access-Control-Allow-Origin *;
            proxy_set_header Access-Control-Max-Age 3600;
            proxy_set_header Access-Control-Expose-Headers Content-Length;

            #proxy_ssl_protocols TLSv1.2 TLSv1.3;
            #proxy_ssl_server_name on;
            #proxy_ssl_verify    on;
            #proxy_ssl_verify_depth  2;


            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;
            proxy_set_header X-Forwarded-Host $http_host;

        }

        location /websocket {
            proxy_headers_hash_bucket_size 128;
            proxy_buffering off;

            proxy_pass http://tendermint_rpc/websocket;

            #ssl certs
            #proxy_ssl_certificate           /etc/letsencrypt/archive/rpc.erialos.me/privkey2.pem;
            #proxy_ssl_certificate_key       /etc/letsencrypt/archive/rpc.erialos.me/fullchain2.pem;
            #proxy_ssl_verify    on;
            #proxy_ssl_verify_depth  2;
            proxy_hide_header   Access-Control-Allow-Origin;
            proxy_set_header           Connection "Keep-Alive";

            #
            # Pingpub CORS proxy
            #
            proxy_set_header Access-Control-Allow-Origin *;
            proxy_set_header Access-Control-Max-Age 3600;
            proxy_set_header Access-Control-Expose-Headers Content-Length;


            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;
            #was https for the forwarded proto
            proxy_set_header X-Forwarded-Host $http_host;
        }

#        error_page 497 = @foobar;
#
#        location @foobar {
#            return 301 https://$host:$server_port$request_uri;
#        }

}
```

GRPC:
```
upstream grpc-proxy {
        server 127.0.0.1:9090;
        #       weight=3 max_conns=1000 max_fails=1000 fail_timeout=360s;
    keepalive 60;
}

upstream grpc-web-proxy {
        server 127.0.0.1:9091;
        #        weight=3 max_conns=1000 max_fails=1000 fail_timeout=360s;
    keepalive 60;
}

server {
        listen 443 ssl http2;

            listen 194.195.209.168:9090;
        server_name grpc.rpc.erialos.me;

        limit_conn servers 100;
        limit_req zone=request burst=10 delay=3;
        limit_rate_after 3m;
        limit_rate $response_rate;


        # Enable logging, set log format
        error_log /var/log/nginx/9090-error.log;

        ssl_certificate_key     /etc/letsencrypt/live/rpc.erialos.me/privkey.pem;
        ssl_certificate         /etc/letsencrypt/live/rpc.erialos.me/fullchain.pem;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
                grpc_pass grpc://grpc-proxy;
        }
        location  /web {
                grpc_pass grpc://grpc-web-proxy;

        }

#        error_page 497 = @foobar;
#
#        location @foobar {
#            return 301 https://$host:$server_port$request_uri;
#        }


}
```

and at the top of my nginx i have:
```
# Proper headers mapping for websocket endpoint
map $http_upgrade $connection_upgrade {
        default Upgrade;
        '' close;
}
```

**Comment by effofxprime** [comment]
Just for testing purposes, I have made these accessible via a non-secure method. This will not stay that way as it is just to eliminate other potential issues.

**Comment by effofxprime** [comment]
Not sure why I didn't think of this before but I think it confirms what I have suspected.
We have a main LCD that is used for the wallet and hosted by the dev team, https://mainnet-rpc.vidulum.app:443 and i tried using that one.
It also fails with the same error when trying to parse staking validators.

I think it is ether to do with my go version, 1.18.1 or, one of the package versions.  Recollecting my thoughts on what changed from when it 'worked' to not working, my changes were updating golang and then I cleared my build dir and rechecked out from stratch.  

Should I need to modify any of the package version in side the go.mod to be match with what is used for the blockchain?

**Comment by effofxprime** [comment]
So, I thought this whole time that the error I was getting was a `websocket` connecction error.  This is a `grpc` error.
Config changes
```
            client_name: bdcosmos
            address: https://trpc.rpc.erialos.me:443
            max_connections: 20
        grpc:
            address: https://grpc.rpc.erialos.me:443
            insecure: false
```

the grpc address is different from before because I have put everyone on ssl again.
```
bdcosmos@erialos:~/bdjuno$ bdjuno parse staking validators
ERROR: error while getting validators: rpc error: code = Unavailable desc = connection closed
bdcosmos@erialos:~/bdjuno$ nano ~/.bdjuno/config.yaml
bdcosmos@erialos:~/bdjuno$ bdjuno parse staking validators
bdcosmos@erialos:~/bdjuno$ cat ~/.bdjuno/config.yaml
```
The first failure shows prior to my change and after shows running it with the change made.  I now do not have any issues pulling validator information.

I also downgraded go, I am on `1.17.9`.  Along with that downgrade, I have also downgraded to 3.0.1 bdjuno.  I will try and change branches to the cosmos v0.44.x and see if that is also working.  I have been trying to retrace my steps since it worked, and I wanted to make sure I documented where I got it working again first before moving on.

**Comment by effofxprime** [comment]
Here are some relevent nginx changes made to help deal/counter act the bug in 0.44.x of cosmos sdk that when RPC services are over utilized, it will cause a concurrent map read and write, crashing the server.

https://github.com/cosmos/cosmos-sdk/issues/11716
The changes I listed/made in the above github issue has "mostly" resolved these issues for me.

I am currently running and collecting all data as expected right now.

I am wondering if some changes could be made to help troubleshoot errors?  specifying trpc/grpc connection type errors would be helpful.  Maybe even baking in the parsing functions to "slow down" and limit the request sent to help minimize the issue as well?  Or a flag that we could define in milliseconds?
